//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAlphaWebsite.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerAlphaWebsite.Locales.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string DisclaimerContinueButton {
            get {
                return ResourceManager.GetString("DisclaimerContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string DisclaimerReverseButton {
            get {
                return ResourceManager.GetString("DisclaimerReverseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to The Martian Game!&lt;br/&gt;&lt;br/&gt;
        ///  We are a group of researchers exploring question asking. By participating in
        ///  The Martian Game, you consent to the collection and use of your gameplay data —
        ///  such as the questions you ask and your responses — for research purposes.
        ///  Your data will be anonymized, aggregated with other participants&apos; data and
        ///  securely stored to protect its confidentiality.&lt;br/&gt;&lt;br/&gt;
        ///  Thank you for your participation, and we hope you enjoy the game!&lt;br/&gt;.
        /// </summary>
        public static string DisclaimerText1 {
            get {
                return ResourceManager.GetString("DisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Martian City Design Challenge!&lt;br/&gt;&lt;br/&gt;
        ///  Your mission is to design a reliable and sustainable energy system for a city on Mars.&lt;br/&gt;To achieve this, you will interact with Mark,
        ///  an AI-powered agent who has the answers to all questions relevant to planning the energy system. Ask creative, analytical, and relevant questions,
        ///  and Mark will provide the information you need. You will earn points based on the quality of your questions, with relevance multiplying your score.&lt;br/&gt;.
        /// </summary>
        public static string DisclaimerText2 {
            get {
                return ResourceManager.GetString("DisclaimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game consists of two parts:&lt;br/&gt;&lt;br/&gt;
        ///
        ///  1. Ask Questions: Gather information by asking the agent as many questions as you like.  After each question, you&apos;ll
        ///  receive feedback and earn points based on the quality and relevance of your inquiry. During the question phase, a short summary
        ///  of each question you ask will appear on the right side of the screen. When you are ready to plan the energy system,
        ///  click &quot;&quot;Finish Asking&quot;&quot; to proceed to the next phase.&lt;br/&gt;&lt;br/&gt;
        ///
        ///  2. Plan Your Energy System [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DisclaimerText3 {
            get {
                return ResourceManager.GetString("DisclaimerText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a look at my solution.
        /// </summary>
        public static string Finish2CheckSolution {
            get {
                return ResourceManager.GetString("Finish2CheckSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here to Proceed.
        /// </summary>
        public static string Finish2Proceed {
            get {
                return ResourceManager.GetString("Finish2Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string Finish2ScoreboardTitle {
            get {
                return ResourceManager.GetString("Finish2ScoreboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for participating and we hope you enjoyed the game!.
        /// </summary>
        public static string Finish2Thanks {
            get {
                return ResourceManager.GetString("Finish2Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish game.
        /// </summary>
        public static string FinishFinishGame {
            get {
                return ResourceManager.GetString("FinishFinishGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an illustration of your energy system..
        /// </summary>
        public static string FinishIllustrationSubtitle {
            get {
                return ResourceManager.GetString("FinishIllustrationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask more questions.
        /// </summary>
        public static string FinishKeepAsking {
            get {
                return ResourceManager.GetString("FinishKeepAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to ask more questions and refine your plan?.
        /// </summary>
        public static string FinishKeepAskingText {
            get {
                return ResourceManager.GetString("FinishKeepAskingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! &lt;br /&gt;&lt;br /&gt; You have completed the game. Your efforts have assisted humans in progressing on their quest to populate Mars. Your responses have been logged and we thank you for participating. &lt;br /&gt;&lt;br /&gt; Your final score is {0} points. &lt;br /&gt; For reference, the average score is {1} points..
        /// </summary>
        public static string FinishText {
            get {
                return ResourceManager.GetString("FinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have scored above average! Well done!.
        /// </summary>
        public static string FinishTextAboveAverage {
            get {
                return ResourceManager.GetString("FinishTextAboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won&apos;t be able to ask any more questions during the design phase.
        ///&lt;br/&gt;
        ///Are you sure that you want to proceed to the design phase?.
        /// </summary>
        public static string GameConfirmationModal {
            get {
                return ResourceManager.GetString("GameConfirmationModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GameConfirmationModalCancel {
            get {
                return ResourceManager.GetString("GameConfirmationModalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really continue.
        /// </summary>
        public static string GameConfirmationModalContinue {
            get {
                return ResourceManager.GetString("GameConfirmationModalContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Asking and Proceed to Design Phase.
        /// </summary>
        public static string GameFinishAsking {
            get {
                return ResourceManager.GetString("GameFinishAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mission is to design a reliable and sustainable energy system for a city on Mars.&lt;br/&gt;To achieve this, you will interact with Mark,
        ///an AI-powered agent who has the answers to all questions relevant to planning the energy system. Ask creative, analytical, and relevant questions,
        ///and Mark will provide the information you need. You will earn points based on the quality of your questions, with relevance multiplying your score.&lt;br/&gt;&lt;br/&gt;
        ///Gather information by asking the agent as many questions as you lik [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GameInformationModal {
            get {
                return ResourceManager.GetString("GameInformationModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string GameInformationModalClose {
            get {
                return ResourceManager.GetString("GameInformationModalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question-asking phase.
        /// </summary>
        public static string GamePhaseTitle {
            get {
                return ResourceManager.GetString("GamePhaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores of players at question #{0}.
        /// </summary>
        public static string GameScoreboardTitle {
            get {
                return ResourceManager.GetString("GameScoreboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read instructions.
        /// </summary>
        public static string GameShowInstructionModal {
            get {
                return ResourceManager.GetString("GameShowInstructionModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string MainMenuStart {
            get {
                return ResourceManager.GetString("MainMenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string QuestionnaireContinueButton {
            get {
                return ResourceManager.GetString("QuestionnaireContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelors degree.
        /// </summary>
        public static string QuestionnaireEducationBachelors {
            get {
                return ResourceManager.GetString("QuestionnaireEducationBachelors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctoral or Professional degree.
        /// </summary>
        public static string QuestionnaireEducationDoctoral {
            get {
                return ResourceManager.GetString("QuestionnaireEducationDoctoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High school diploma or equivalent.
        /// </summary>
        public static string QuestionnaireEducationHighSchool {
            get {
                return ResourceManager.GetString("QuestionnaireEducationHighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters degree.
        /// </summary>
        public static string QuestionnaireEducationMasters {
            get {
                return ResourceManager.GetString("QuestionnaireEducationMasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string QuestionnaireEducationOther {
            get {
                return ResourceManager.GetString("QuestionnaireEducationOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some college or university (No degree).
        /// </summary>
        public static string QuestionnaireEducationSome {
            get {
                return ResourceManager.GetString("QuestionnaireEducationSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string QuestionnaireGenderFemale {
            get {
                return ResourceManager.GetString("QuestionnaireGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string QuestionnaireGenderMale {
            get {
                return ResourceManager.GetString("QuestionnaireGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer not to Say.
        /// </summary>
        public static string QuestionnaireGenderNaN {
            get {
                return ResourceManager.GetString("QuestionnaireGenderNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Binary.
        /// </summary>
        public static string QuestionnaireGenderNonBinary {
            get {
                return ResourceManager.GetString("QuestionnaireGenderNonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string QuestionnaireNo {
            get {
                return ResourceManager.GetString("QuestionnaireNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string QuestionnaireQuestion1Title {
            get {
                return ResourceManager.GetString("QuestionnaireQuestion1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string QuestionnaireQuestion2Title {
            get {
                return ResourceManager.GetString("QuestionnaireQuestion2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is English your first language?.
        /// </summary>
        public static string QuestionnaireQuestion3Title {
            get {
                return ResourceManager.GetString("QuestionnaireQuestion3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string QuestionnaireQuestion4Title {
            get {
                return ResourceManager.GetString("QuestionnaireQuestion4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education:.
        /// </summary>
        public static string QuestionnaireQuestion5Title {
            get {
                return ResourceManager.GetString("QuestionnaireQuestion5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string QuestionnaireSubmitButton {
            get {
                return ResourceManager.GetString("QuestionnaireSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are willing, please enter the following demographic details to help us be more accurate.
        ///                You will access the game after you do so.&lt;br/&gt;Ensure that you don&apos;t make any mistakes, since you won&apos;t have a chance to edit the questionnaire later on..
        /// </summary>
        public static string QuestionnaireTitle {
            get {
                return ResourceManager.GetString("QuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string QuestionnaireYes {
            get {
                return ResourceManager.GetString("QuestionnaireYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m done!.
        /// </summary>
        public static string SolutionFinish {
            get {
                return ResourceManager.GetString("SolutionFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you submit your design, we will create an image for you that illustrates the nature of the system..
        /// </summary>
        public static string SolutionSubtitle {
            get {
                return ResourceManager.GetString("SolutionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize.
        /// </summary>
        public static string SolutionSummarize {
            get {
                return ResourceManager.GetString("SolutionSummarize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design phase.
        /// </summary>
        public static string SolutionTitle {
            get {
                return ResourceManager.GetString("SolutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your solution here:.
        /// </summary>
        public static string SolutionTitleInstruction {
            get {
                return ResourceManager.GetString("SolutionTitleInstruction", resourceCulture);
            }
        }
    }
}
